[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version="0.8.1", features=["ws", "tokio"]}
futures = "0.3.31"
once_cell = "1.21.1"
serde_json = "1.0.140"
sqlite = "0.36.2"
tokio = {version="1.44.1", features=["full"]}


